blood_management_system/blood_management_system/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('common.urls')),
    path('patient/',include('patient.urls'))

]

blood_management_system/common/urls.py
from django.urls import path
from . import views
app_name = 'common_app'

urlpatterns = [
    path('', views.common_index,name='index'),
    path('about',views.about,name='about'),
    path('blog',views.blog,name='blog'),
    path('contact',views.contact,name='contact'),
    path('what_is_bms',views.bms_details,name='what_is_bms'),
    path('login',views.login,name='login'),
    path('register',views.register,name='register'),
    path('taluk',views.taluk,name='taluk')
   
   
]

blood_management_system/patient/urls.py
from django.urls import path
from . import views
app_name = 'patient_app'
urlpatterns = [
    path('', views.patient_index,name='index'),
    path('about',views.about,name='about'),
    path('blog',views.blog,name='blog'),
    path('contact',views.contact,name='contact'),
    path('what_is_bms',views.bms_details,name='what_is_bms'),
  

    
   
   
]

blood_management_system/common/models.py
from django.db import models

# Create your models here.

class District(models.Model):
    name = models.CharField(max_length=40)


class Taluk(models.Model):
    district= models.ForeignKey(District, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)

class Blood_bank(models.Model):
    dist= models.ForeignKey(District, on_delete=models.CASCADE)
    bank_name = models.CharField(max_length=40)
    class Meta:
        db_table = 'blood_bank'

blood_management_system/patient/models.py
from django.db import models

# Create your models here.

blood_management_system/common/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import District,Taluk,Blood_bank

# Create your views here.

def common_index(request):
    return render(request,'common_templates/index.html')

def about(request):
    return render(request,'common_templates/about.html')

def blog(request):
    return render(request,'common_templates/blog.html')

def contact(request):
    return render(request,'common_templates/contact.html')

def  bms_details(request):
    return render(request,'common_templates/what_is_bms.html')

def  login(request):
    return render(request,'common_templates/common_login.html')

def  register(request):
    return render(request,'common_templates/register_to_donate.html')

def  taluk(request):
    
    dis_id = request.POST['dis_id']
 
    taluk = Taluk.objects.filter(district_id = dis_id)
    blood_bank = Blood_bank.objects.filter(dist_id =dis_id)
    print(taluk)
    
    serialized_set = [{'t_name':t.name} for t in taluk]
    
    serialized_blood_bank = [{'b_name':b.bank_name} for b in blood_bank]
    
    return JsonResponse({'taluk':serialized_set,'blood_bank':serialized_blood_bank})

blood_management_system/patient/views.py
from django.shortcuts import render

# Create your views here.

def patient_index(request):
    return render(request,'patient_templates/index.html')

def about(request):
    return render(request,'patient_templates/about.html')

def blog(request):
    return render(request,'patient_templates/blog.html')

def contact(request):
    return render(request,'patient_templates/contact.html')

def  bms_details(request):
    return render(request,'patient_templates/what_is_bms.html')

blood_management_system/common/templates/common_templates/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Charity &mdash; 100% Free Fully Responsive HTML5 Template by FREEHTML5.co</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Template by FREEHTML5.CO" />
	<meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
	<meta name="author" content="FREEHTML5.CO" />

  <!-- 
	//////////////////////////////////////////////////////

	FREE HTML5 TEMPLATE 
	DESIGNED & DEVELOPED by FREEHTML5.CO
		
	Website: 		http://freehtml5.co/
	Email: 			info@freehtml5.co
	Twitter: 		http://twitter.com/fh5co
	Facebook: 		https://www.facebook.com/fh5co

	//////////////////////////////////////////////////////
	 -->

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">

	<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
	
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<!-- Superfish -->
	<link rel="stylesheet" href="{% static 'css/superfish.css' %}">

	<link rel="stylesheet" href="{% static 'css/style.css' %}">


	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->
      
    <!----------------------------seperate css link------------------------->
    {% block link%} {% endblock %}
	</head>

    <body>

        {% block content %}  {% endblock %}
    </body>

</html>

blood_management_system/common/templates/common_templates/common_login.html
{% extends './base.html' %}
{% load static %}
{% block link %} <link rel="stylesheet" href="{% static 'css/common_login.css' %}"> {% endblock %}
{%block content%}
    
    
<div id="fh5co-wrapper">
	<div id="fh5co-page">
	<div class="header-top">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-sm-6 text-left fh5co-link">
					<a href="{% url 'common_app:register' %}">Register</a>
					<a href="{% url 'common_app:login' %}">Login</a>
					<a href="#">Contact</a>
				</div>
				<div class="col-md-6 col-sm-6 text-right fh5co-social">
					<a href="#" class="grow"><i class="icon-facebook2"></i></a>
					<a href="#" class="grow"><i class="icon-twitter2"></i></a>
					<a href="#" class="grow"><i class="icon-instagram2"></i></a>
				</div>
			</div>
		</div>
	</div>
	<header id="fh5co-header-section" class="sticky-banner">
		<div class="container">
			<div class="nav-header">
				<a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle dark"><i></i></a>
				<h1 id="fh5co-logo"><a href="index.html">Blood <span style="color:#181a1a;">Wings</span></a></h1>
				<!-- START #fh5co-menu-wrap -->
				<nav id="fh5co-menu-wrap" role="navigation">
					<ul class="sf-menu" id="fh5co-primary-menu">
						<li class="active">
							<a href="{% url 'common_app:index' %}">Home</a>
						</li>
						<li>
							<a href="#" class="fh5co-sub-ddown">Blood Banks</a>
							 <ul class="fh5co-sub-menu">
								 <li><a href="#">Events</a></li>
								 <li><a href="#"></a></li>
								 <li><a href="#">Medical Mission</a></li>
							</ul>
						</li>
						<li><a href="{% url 'common_app:about' %}">About</a></li>
						<li><a href="{% url 'common_app:blog' %}">Blog</a></li>
						<li><a href="{% url 'common_app:contact' %}">Contact</a></li>
						<li>
							<a href="#" class="fh5co-sub-ddown">Get Involved</a>
							<ul class="fh5co-sub-menu">
								<li><a href="#">Donate</a></li>
								<li><a href="#">Blood request</a></li>
								<li><a href="#">Contact Us</a></li>
								
							</ul>
						</li>
					</ul>
				</nav>
			</div>
		</div>
	</header>

    
		<div id="fh5co-contact" class="animate-box" >
			<div class="container ">
				<div class="row">
					<div class="col-md-12 text-center heading-section">
						<h3>Blood Donor Login</h3>
						<!-- <p>The donation process from the time you arrive center until the time you leave</p> -->
					</div>
				</div>
				<form action="#">
					<div class="row">			
		     			<div class="col-md-12">   
								<div class="col-md-12">
									<div class="form-group">
									<label for="">Email</label>&nbsp;&nbsp;<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-at-fill" viewBox="0 0 16 16">
										<path d="M2 2A2 2 0 0 0 .05 3.555L8 8.414l7.95-4.859A2 2 0 0 0 14 2H2Zm-2 9.8V4.698l5.803 3.546L0 11.801Zm6.761-2.97-6.57 4.026A2 2 0 0 0 2 14h6.256A4.493 4.493 0 0 1 8 12.5a4.49 4.49 0 0 1 1.606-3.446l-.367-.225L8 9.586l-1.239-.757ZM16 9.671V4.697l-5.803 3.546.338.208A4.482 4.482 0 0 1 12.5 8c1.414 0 2.675.652 3.5 1.671Z"/>
										<path d="M15.834 12.244c0 1.168-.577 2.025-1.587 2.025-.503 0-1.002-.228-1.12-.648h-.043c-.118.416-.543.643-1.015.643-.77 0-1.259-.542-1.259-1.434v-.529c0-.844.481-1.4 1.26-1.4.585 0 .87.333.953.63h.03v-.568h.905v2.19c0 .272.18.42.411.42.315 0 .639-.415.639-1.39v-.118c0-1.277-.95-2.326-2.484-2.326h-.04c-1.582 0-2.64 1.067-2.64 2.724v.157c0 1.867 1.237 2.654 2.57 2.654h.045c.507 0 .935-.07 1.18-.18v.731c-.219.1-.643.175-1.237.175h-.044C10.438 16 9 14.82 9 12.646v-.214C9 10.36 10.421 9 12.485 9h.035c2.12 0 3.314 1.43 3.314 3.034v.21Zm-4.04.21v.227c0 .586.227.8.581.8.31 0 .564-.17.564-.743v-.367c0-.516-.275-.708-.572-.708-.346 0-.573.245-.573.791Z"/>
									  </svg>
                                      <input type="text" id="email" class="form-control" placeholder="Example@gmail.com">
									</div>
								</div>
                                <div class="col-md-12">
									<div class="form-group">
                                        <label for="">password</label>&nbsp;&nbsp;<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lock-fill" viewBox="0 0 16 16">
											<path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2z"/>
										  </svg>
										<input type="text" class="form-control" placeholder="password">
									</div>
								</div>
								<div class="col-md-12 ">
									<div class="form-group">
										<input type="submit"id="Login_btn" value="Login Now" class="btn btn-primary">
										<input type="submit" id="Join_btn" value="Join to Donate" class="btn btn-outline">
									</div>
								</div>
								<div class="col-md-12">
									<a href="" id="Reset_pswd">Reset password</a>
									

								</div>
                                
							</div>
				
						</div>
					</form>
			</div>
				
		</div>
		
		<!-- END fh5co-contact -->





    <!-- fh5co-blog-section -->
	<footer>
		<div id="footer">
			<div class="container">
				<div class="row">
					<div class="col-md-6 col-md-offset-3 text-center">
						<p class="fh5co-social-icons">
							<a href="#"><i class="icon-twitter2"></i></a>
							<a href="#"><i class="icon-facebook2"></i></a>
							<a href="#"><i class="icon-instagram"></i></a>
							<a href="#"><i class="icon-dribbble2"></i></a>
							<a href="#"><i class="icon-youtube"></i></a>
						</p>
						<p>Copyright 2016 Free Html5 <a href="#">Charity</a>. All Rights Reserved. <br>Made with <i class="icon-heart3"></i> by <a href="http://freehtml5.co/" target="_blank">Freehtml5.co</a> / Demo Images: <a href="https://unsplash.com/" target="_blank">Unsplash</a></p>
					</div>
				</div>
			</div>
		</div>
	</footer>


</div>
<!-- END fh5co-page -->

</div>
<!-- END fh5co-wrapper -->

<!-- jQuery -->


<script src="{% static  'js/jquery.min.js' %}"></script>
<!-- jQuery Easing -->
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Waypoints -->
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/sticky.js' %}"></script>

<!-- Stellar -->
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<!-- Superfish -->
<script src="{% static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/superfish.js' %}"></script>

<!-- Main JS -->
<script src="{% static 'js/main.js' %}"></script>







{% endblock %}

blood_management_system/common/templates/common_templates/index.html
{% extends './base.html' %}
{% load static %}
{% block link %} <link rel="stylesheet" href="{% static 'css/common_index.css' %}"> {% endblock %}
{%block content%}


	<div id="fh5co-wrapper">
	<div id="fh5co-page">
	<div class="header-top">
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-sm-6 text-left fh5co-link">
					<a href="{% url 'common_app:register' %}">Register</a>
					<a href="{% url 'common_app:login' %}">Login</a>
					<a href="#">Contact</a>
				</div>
				<div class="col-md-6 col-sm-6 text-right fh5co-social">
					<a href="#" class="grow"><i class="icon-facebook2"></i></a>
					<a href="#" class="grow"><i class="icon-twitter2"></i></a>
					<a href="#" class="grow"><i class="icon-instagram2"></i></a>
				</div>
			</div>
		</div>
	</div>
	<header id="fh5co-header-section" class="sticky-banner">
		<div class="container">
			<div class="nav-header">
				<a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle dark"><i></i></a>
				<h1 id="fh5co-logo"><a href="index.html">Blood <span style="color:#181a1a;">Wings</span></a></h1>
				<!-- START #fh5co-menu-wrap -->
				<nav id="fh5co-menu-wrap" role="navigation">
					<ul class="sf-menu" id="fh5co-primary-menu">
						<li class="active">
							<a href="{% url 'common_app:index' %}">Home</a>
						</li>
						<li>
							<a href="#" class="fh5co-sub-ddown">Blood Banks</a>
							 <ul class="fh5co-sub-menu">
								 <li><a href="#">Events</a></li>
								 <li><a href="#"></a></li>
								 <li><a href="#">Medical Mission</a></li>
							</ul>
						</li>
						<li><a href="{% url 'common_app:about' %}">About</a></li>
						<li><a href="{% url 'common_app:blog' %}">Blog</a></li>
						<li><a href="{% url 'common_app:contact' %}">Contact</a></li>
						<li>
							<a href="#" class="fh5co-sub-ddown">Get Involved</a>
							<ul class="fh5co-sub-menu">
								<li><a href="#">Donate</a></li>
								<li><a href="#">Blood request</a></li>
								<li><a href="#">Contact Us</a></li>
								
							</ul>
						</li>
					</ul>
				</nav>
			</div>
		</div>
	</header>
	
	

	<div class="fh5co-hero">
		<div class="fh5co-overlay"></div>
		<div class="fh5co-cover text-center" data-stellar-background-ratio="0.5" style="background-image: url('static/images/cover1.jpg');">
			<div class="desc animate-box">
				<h2><strong>Donate ! </strong>It  is  a <strong>bloody  good  job</strong></h2>
				<br>
				<p id="cover1_para"> you can give blood at any of our blood donation venues all over the world. We have a total of sixty thousand donor <br> centers and visit thousands of other venues on occasion</p>
				<br><br>
				<span><a class="btn btn-primary btn-lg cover1_btn " href="#">Blood Donate</a></span>
				&nbsp;
				<span><a class="btn btn-primary btn-lg cover1_btn" href="#">Blood request</a></span>
			</div>
		</div>

	</div>
	<!-- end:header-top -->
	<div id="fh5co-features">
		<div class="container">
			<div class="row">
				<div class="col-md-4">

					<div class="feature-left">
						<span class="icon">
							<i class="icon-profile-male"></i>
						</span>
						<div class="feature-copy">
							<h3>What is Blood Banking ?</h3>
							<p>facts about blood banking <br>According to the American Association of Blood Banks as of 2013:</p>
							<p><a href="{% url 'common_app:what_is_bms' %}">Learn More</a></p>
						</div>
					</div>

				</div>

				<div class="col-md-4 ">
					<div class="feature-left">
						<span class="icon">
							<i class="icon-happy"></i>
						</span>
						<div class="feature-copy">
							<h3>tips</h3>
							<p>Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit.</p>
							<p><a href="#">Learn More</a></p>
						</div>
					</div>

				</div>
				<div class="col-md-4">
					<div class="feature-left">
						<span class="icon">
							<i class="icon-wallet"></i>
						</span>
						<div class="feature-copy">
							<h3>Donation</h3>
							<p>Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit.</p>
							<p><a href="#">Learn More</a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div id="fh5co-feature-product" class="fh5co-section-gray">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center heading-section animate-box">
					<h3>The Blood Donor Register Wth Bood Wings </h3>
			
				</div>
			</div>
			<div class="row ">	

				<div class="col-xs-6 col-sm-3 col-md-3"> 
				    <button class="btn-lg   donor_btn">A-</button>	
			    </div>                            
		
				<div class="col-xs-6 col-sm-3 col-md-3">    
				    <button class="btn-lg    donor_btn">A+</button>								  
				</div>
					  
				<div class="col-xs-6 col-sm-3 col-md-3">
				    <button class="btn-lg    donor_btn">AB-</button>										   
				</div>  
				
				<div class="col-xs-6 col-sm-3 col-md-3">
				    <button class="btn-lg   donor_btn ">AB+</button>		   
				 </div>	  		  
					
				<div class="col-xs-6 col-sm-3 col-md-3">	  
					<button class="btn-lg  donor_btn">B-</button>		  
				</div>                            		
						
				<div class="col-xs-6 col-sm-3 col-md-3">		 
					<button class="btn-lg   donor_btn">B+</button>																	
				</div>
									 
				<div class="col-xs-6 col-sm-3 col-md-3">
					<button class="btn-lg   donor_btn">O-</button>				  
				</div>
				
				<div class="col-xs-6 col-sm-3 col-md-3">
                    <button class="btn-lg  donor_btn ">O+</button> 
				</div>
			</div>

			<div class="row">
				<div class="col-xs-12">
					<br><br>
					<h3>ALL BLOOD GROUP LIST</h3>	
				</div>	
			</div>
		</div>

			
	</div>
	<marquee id="marquee_text">
		Do not pay any amount to any person or organization promising supply of blood packets or arranging blood donors :: You can donate blood after 14 days of your any or each dose of covid 19 vaccination in india if you are eligible as per the blood donation criteria.
		</marquee>
	

	
	<!-- <div id="fh5co-portfolio">
		<div class="container">

			<div class="row">
				<div class="col-md-6 col-md-offset-3 text-center heading-section animate-box">
					<h3>Our Gallery</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit est facilis maiores, perspiciatis accusamus asperiores sint consequuntur debitis.</p>
				</div>
			</div>

			
			<div class="row row-bottom-padded-md">
				<div class="col-md-12">
					<ul id="fh5co-portfolio-list">

						<li class="two-third animate-box" data-animate-effect="fadeIn" style="background-image: url('static/images/cover_bg_1.jpg'); ">
							<a href="#" class="color-3">
								<div class="case-studies-summary">
									<span>Give Love</span>
									<h2>Donation is caring</h2>
								</div>
							</a>
						</li>
					
						<li class="one-third animate-box" data-animate-effect="fadeIn" style="background-image: url('static/images/cover_bg_3.jpg'); ">
							<a href="#" class="color-4">
								<div class="case-studies-summary">
									<span>Give Love</span>
									<h2>Donation is caring</h2>
								</div>
							</a>
						</li>

						<li class="one-third animate-box" data-animate-effect="fadeIn" style="background-image: url('static/images/cover_bg_1.jpg'); "> 
							<a href="#" class="color-5">
								<div class="case-studies-summary">
									<span>Give Love</span>
									<h2>Donation is caring</h2>
								</div>
							</a>
						</li>
						<li class="two-third animate-box" data-animate-effect="fadeIn" style="background-image: url('static/images/cover_bg_3.jpg'); ">
							<a href="#" class="color-6">
								<div class="case-studies-summary">
									<span>Give Love</span>
									<h2>Donation is caring</h2>
								</div>
							</a>
						</li>
					</ul>		
				</div>
			</div>

			<div class="row">
				<div class="col-md-4 col-md-offset-4 text-center animate-box">
					<a href="#" class="btn btn-primary btn-lg">See Gallery</a>
				</div>
			</div>

			
		</div>
	</div> -->
	
	<div id="fh5co-content-section" class="fh5co-section-gray">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center heading-section animate-box">
					<h3  id="vision_headding" >Our Philantrophist</h3>
					<p id="vision_para">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit est facilis maiores, perspiciatis accusamus asperiores sint consequuntur debitis.</p>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<div class="fh5co-testimonial text-center animate-box">
						<figure>
							<img  src="{% static 'images/binocular.png' %}" alt="user">
						</figure>
						<blockquote>
							<p>&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;</p>
						</blockquote>
						<span>Jean Doe, XYZ Co.</span>
					</div>
				</div>
				<div class="col-md-4">
					<div class="fh5co-testimonial text-center animate-box">
						<figure>
							<img src="{% static 'images/goal.png' %}" alt="user">
						</figure>
						<blockquote>
							<p>&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;</p>
						</blockquote>
						<span>John Doe, XYZ Co.</span>
					</div>
				</div>
				<div class="col-md-4">
					<div class="fh5co-testimonial text-center animate-box">
						<figure>
							<img src="{% static 'images/drop1.png' %}" alt="user">
						</figure>
						<blockquote>
							<p>&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;</p>
						</blockquote>
						<span>John Doe, XYZ Co.</span>
					</div>
				</div>
			</div>
		</div>
	</div>
	

	<!-- END What we do -->

	<!-- fh5co-blog-section -->
	<footer>
		<div id="footer">
			<div class="container">
				<div class="row">
					<div class="col-md-6 col-md-offset-3 text-center">
						<p class="fh5co-social-icons">
							<a href="#"><i class="icon-twitter2"></i></a>
							<a href="#"><i class="icon-facebook2"></i></a>
							<a href="#"><i class="icon-instagram"></i></a>
							<a href="#"><i class="icon-dribbble2"></i></a>
							<a href="#"><i class="icon-youtube"></i></a>
						</p>
						<p>Copyright 2016 Free Html5 <a href="#">Charity</a>. All Rights Reserved. <br>Made with <i class="icon-heart3"></i> by <a href="http://freehtml5.co/" target="_blank">Freehtml5.co</a> / Demo Images: <a href="https://unsplash.com/" target="_blank">Unsplash</a></p>
					</div>
				</div>
			</div>
		</div>
	</footer>


</div>
<!-- END fh5co-page -->

</div>
<!-- END fh5co-wrapper -->

<!-- jQuery -->


<script src="{% static  'js/jquery.min.js' %}"></script>
<!-- jQuery Easing -->
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Waypoints -->
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/sticky.js' %}"></script>

<!-- Stellar -->
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<!-- Superfish -->
<script src="{% static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/superfish.js' %}"></script>

<!-- Main JS -->
<script src="{% static 'js/main.js' %}"></script>







{% endblock %}